### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by shishishi1320** [shishishi1320/chat-space#6]
＃IPアドレス
54.65.99.124

**Comment by yasunamiura** [comment]
白田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①ユーザーをインクリメンタルサーチできるようにしましょう**
<img width="1070" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/79084426-a8cb6d00-7d6e-11ea-9e83-6ae70b34fb8f.png">
該当カリキュラム
https://master.tech-camp.in/curriculums/3708

**②非同期・自動更新時にビューが大きく崩れているので直しましょう**
![screencapture-54-65-99-124-groups-3-messages-2020-04-13-10_10_05](https://user-images.githubusercontent.com/52514431/79084493-0790e680-7d6f-11ea-8e7b-985e463205ff.png)
模範
<img width="759" alt="ChatSpace_フロント実装" src="https://user-images.githubusercontent.com/52514431/79084709-1f1c9f00-7d70-11ea-847c-758296d0f043.png">


以下CSSの修正です
**③こちら不要です**
**④文頭にMember:を追加し、文字サイズを直しましょう**
**⑤Editの文字色を水色にしましょう**
**⑥ボタン位置を模範の通りにしましょう**
![ChatSpaceSample](https://user-images.githubusercontent.com/52514431/79084590-838b2e80-7d6f-11ea-911a-21afac7d56fd.png)
模範
<img width="748" alt="ChatSpace_フロント実装" src="https://user-images.githubusercontent.com/52514431/79084664-eda3d380-7d6f-11ea-8498-dc841d02556c.png">
<img width="745" alt="ChatSpace_フロント実装" src="https://user-images.githubusercontent.com/52514431/79084719-2c398e00-7d70-11ea-9616-5c0313d4cefc.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shishishi1320** [comment]
修正しました

**Comment by miyu-yamamoto** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ 非同期・自動更新時にビューが大きく崩れているので直しましょう**
**○ 新規チャットグループが作成画面にて、グループ名とメンバーを入力する項目が逆に表示されている**
**○ ユーザーをインクリメンタルサーチできるようにしましょう**
**○ チャットメンバーの表示が見本と相違している**
<img width="1148" alt="スクリーンショット 2020-04-13 15 28 27" src="https://user-images.githubusercontent.com/59544869/79098208-6b7dd400-7d9c-11ea-95f2-c3d11e56221f.png">

`↓こちらが見本です`
<img width="990" alt="スクリーンショット 2020-04-13 15 38 33" src="https://user-images.githubusercontent.com/59544869/79098441-ee069380-7d9c-11ea-8a98-1724827d2fa9.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shishishi1320** [comment]
修正しました。

**Comment by yasunamiura** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①自動更新できるようにしましょう**
<img width="1389" alt="ChatSpaceSample_と_ChatSpaceSample_と_tech-camp_と_Hyper_と_メモ" src="https://user-images.githubusercontent.com/52514431/79103512-b05b3800-7da7-11ea-8aa7-8478056fdac8.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shishishi1320** [comment]
自動更新直しました。

**Comment by miyu-yamamoto** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ 編集ページに飛んだ時に、既存のメンバー全員が「チャットメンバー」として表示されていない**
**○ 縮小表示した時左右にスクロールすると画面が見切れてしまう**
<img width="1405" alt="スクリーンショット 2020-04-13 17 57 17" src="https://user-images.githubusercontent.com/59544869/79108186-c3263a80-7db0-11ea-8476-46980511667a.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shishishi1320** [comment]
直しました。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
